### ISSUE TITLE
Cannot use string formatter in outputReport

### ISSUE THREAD

**Issue by danvim** [webpack-contrib/eslint-loader#289]
- Operating System: Win10
- Node Version: v8.10.0
- NPM Version: 6.10.1
- webpack Version: 4.35.3
- eslint-loader Version: 2.2.1

### Expected Behavior

This setting should output an HTML report

### Actual Behavior

Terminal:

```
ERROR in ./xxxxxxxx.ts
Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: config.outputReport.formatter is not a function
    at printLinterOutput (C:\xxxxxxxx\node_modules\eslint-loader\index.js:95:46)
    at Object.module.exports (C:\xxxxxxxx\node_modules\eslint-loader\index.js:273:3)
 @ ./xxxxxxxx.ts 8:32-52
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./xxxxxxxx.vue?vue&type=script&lang=js&
 @ ./xxxxxxxx.vue?vue&type=script&lang=js&
...
```

The source code of `eslint-loader` has specified: https://github.com/webpack-contrib/eslint-loader/blob/master/index.js#L95

```javascript
//...
        // if a different formatter is passed in as an option use that
        if (config.outputReport.formatter) {
          reportOutput = config.outputReport.formatter(res.results);  //<---
        } else {
          reportOutput = messages;
        }
//...
```

But the README has this exact example. However, using these settings would still fail in my case.

```javascript
module.exports = {
  entry: "...",
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: "eslint-loader",
        options: {
          outputReport: {
            filePath: "checkstyle.xml",
            formatter: "checkstyle"
          }
        }
      }
    ]
  }
};
```

### Code

```javascript
//...
  {
    enforce: 'pre',
    exclude: /node_modules/,
    loader: 'eslint-loader',
    test: /\.(js|vue|ts)$/,
    options: {
      configFile: './.eslintrc.js',
      failOnWarning: true,
      failOnError: true,
      formatter: require('eslint-formatter-friendly'),
      outputReport: {
        filePath: './eslint_report.html',
        formatter: 'html',
      },
    },
  },
//...
```

### How Do We Reproduce?

Use the `outputReport` option and specify a string `formatter`.

**Comment by ricardogobbosouza** [comment]
@danvim yu're right
try use `require`, like this:
```js
options: {
  outputReport: {
    filePath: 'checkstyle.xml',
    formatter: require('eslint-formatter-friendly')
  }
}
```

**Comment by ricardogobbosouza** [comment]
I'm refactoring eslint-loader
